"""Make unneeded verification columns nullable

Revision ID: 2a727696ab1a
Revises: 1a0c2cdafb38
Create Date: 2014-03-31 14:44:57.926258

"""

# revision identifiers, used by Alembic.
revision = '2a727696ab1a'
down_revision = '1a0c2cdafb38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verifications', 'impersonation_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('verifications', 'resource_action',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('verifications', 'resource_ref',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('verifications', 'resource_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verifications', 'resource_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('verifications', 'resource_ref',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('verifications', 'resource_action',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('verifications', 'impersonation_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###
